apiVersion: v1
kind: ServiceAccount
metadata:
  name: steering-viewer
  namespace: admin-vanilla-steering
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: admin-vanilla-steering-view
subjects:
  - kind: ServiceAccount
    name: steering-viewer
    namespace: admin-vanilla-steering
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
