apiVersion: v1
kind: Secret
metadata:
  name: admin-vanilla-secret
type: Opaque
stringData:
  DATABASE_URL: postgresql+psycopg2://newhomepage:change_me_dev@postgres:5432/newhomepage
  POSTGRES_DB: newhomepage
  POSTGRES_USER: newhomepage
  POSTGRES_PASSWORD: change_me_dev
  JWT_SECRET_KEY: replace-with-dev-secret
